spring:
  rabbitmq:
    host: localhost
    username: nsmqreader
    password: 2311
    virtual-host: ns
    template:
      exchange: netspectator-exchange
      logs-routing-key: nsLogs2311
      notifivation-routing-key: nsNotifications2311