90server:
  port: ${SERVER_PORT:9090}
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost:5435}/${DB_NAME:ns-user-manage}
    username: ${DB_USER:w0id}
    password: ${DB_PASSWORD:2311}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create