server:
  port: ${IS_PORT:8083}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://keycloak-postgres:5432/db_is}
    username: ${IS_DB_USER:spring_user}
    password: ${IS_DB_PASSWORD:157456Lb}
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  rabbitmq:
    template:
      exchange: netspectator-exchange
    host: ${MQ_HOST:localhost}
    username: ${MQ_USERNAME:name}
    password: ${MQ_PASSWORD:123}
    virtual-host: ns
user_service:
  host: ${US_HOST:localhost}
  port: ${US_PORT:8080}