server:
  port: ${SERVER_PORT:8181}
  servlet:
    context-path: /core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://keycloak-postgres:5432/deviceService}
    username: ${DB_USERNAME:w0id}
    password: ${DB_PASSWORD:2311}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
  main:
    allow-circular-references: true

