server:
  port: 8181
  servlet:
    context-path: /core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/deviceService
    username: w0id
    password: 2311
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
  main:
    allow-circular-references: true

