server:
  port: 9100
logging:
  level:
#    root: debug
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: trace
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${INTROSPECTION_URI:http://keycloak:8080/realms/netspectator/protocol/openid-connect/token/introspect}
          client-id: javaclient
          client-secret: ZnMtpRXWvGO3h4CSHAGmAtAanTfTAuri
  cloud:
    gateway:
      redis:
        enabled: false
      routes:
        - id: users
          uri: ${USER_URI:http://user-svc:9090}
          predicates:
            - Path=/api/v1/users/**
        - id: checkUser
          uri: ${USER_MANAGE_URI:http://user-manage-svc:9080}
          predicates:
            - Path=/api/v1/check/**
introspect_field: sub