server:
  port: ${SERVER_PORT:9080}
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${INTROSPECTION_URI:http://keycloak:8080/realms/netspectator/protocol/openid-connect/token/introspect}
          client-id: javaclient
          client-secret: ZnMtpRXWvGO3h4CSHAGmAtAanTfTAuri
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://keycloak-postgres:5432/ns-user-manage}
    username: ${DB_USERNAME:w0id}
    password: ${DB_PASSWORD:2311}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create
  task:
    scheduling:
      pool:
        size: 5
check-delay: 60000
realm: ${REALM:netspectator}
type-attribute: ${TYPE_ATTR:ns_user}
keycloak:
  management:
    props:
      server-url: ${KEYCLOAK_SERVER_URI:http://keycloak:8080/}
      master-realm: ${REALM:netspectator}
      username: ${KC_USERNAME:ns-reader}
      password: ${KC_PASSWORD:2311}
      client-id: admin-cli