server:
  port: 9090
spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:9500/realms/netspectator/protocol/openid-connect/token/introspect
          client-id: javaclient
          client-secret: ZnMtpRXWvGO3h4CSHAGmAtAanTfTAuri
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ns-user-manage
    username: w0id
    password: 2311
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: create
  task:
    scheduling:
      pool:
        size: 5
check-delay: 60000
realm: netspectator
keycloak:
  management:
    props:
      server-url: http://localhost:9500/
      master-realm: master
      username: ns-reader
      password: 2311
      client-id: admin-cli